### ISSUE TITLE
Can you please explain encoder and decoder architectures?

### ISSUE THREAD

**Issue by ahsanfarooqui** [razIove/NAS-DGCNN#1]
Hello. Just wanted to know if you can please explain a bit why you used encoder-decoder model in DGCNN model class?

**Comment by razIove** [comment]
Hi, this is the original DGCNN architecture. It is just divided into two parts for searching.

**Comment by ahsanfarooqui** [comment]
Hello. Can you please also mention how to train the teacher model? I did multistage training but the kd_ratio was 0 by default in all cases. will the following script run and save the best model as the teacher model? 

https://github.com/razIove/NAS-DGCNN#run-the-training-script-with-knowledge-distillation-for-each-stage

**Comment by razIove** [comment]
You can use any checkpoint you have trained as the teacher model, e.g., the latest/best model after multistage training, or the orininal DGCNN model
