### ISSUE TITLE
How to get teacher model?

### ISSUE THREAD

**Issue by OGitHub-Cj** [razIove/NAS-DGCNN#2]
In your published paper, the detail of Knowledge Distillation is described as follows "To obtain higher accuracy, we repeat the training procedure twice. The best network and weights obtained in the first training are used as a teacher model to improve subnets by knowledge distillation. The output of the teacher network is used as a soft label to guide the model training through cross entropy loss.". I still don't know how to get the best network as teacher model, can you help me？

**Comment by razIove** [comment]
see https://github.com/razIove/NAS-DGCNN/issues/1#issuecomment-1294646088
